FROM ubuntu:latest

# 设置ARK服务器的Steam ID和环境变量
ENV STEAM_ID=376030 \
    STEAM_USER=anonymous \
    INSTALL_DIR='/home/steam/arkserver' \
    STEAMCMD_PATH='/home/steam/steamcmd' 

# 安装必要的软件包
RUN apt-get update && \
    apt-get install -y \
    lib32gcc-s1 \
    curl \
    ca-certificates && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    # 创建steam用户
    useradd -m -s /bin/bash steam 

# 安装SteamCMD
RUN mkdir -p ${STEAMCMD_PATH} && \
    cd ${STEAMCMD_PATH} && \
    curl -sqL "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz" | tar zxvf - && \
    chmod 777 * && \
    # Create symlink for executable
    ln -s ${STEAMCMD_PATH}/steamcmd.sh /usr/bin/steamcmd

USER steam

# 下载和安装ARK服务器
RUN mkdir -p $INSTALL_DIR && \
    cd ${STEAMCMD_PATH} && \
    ./steamcmd.sh +@sSteamCmdForcePlatformType windows +force_install_dir $INSTALL_DIR +login $STEAM_USER +app_update $STEAM_ID validate +quit && \
    # 清理SteamCMD缓存文件
    rm -rf ${STEAMCMD_PATH}/Steam/logs/* ${STEAMCMD_PATH}/Steam/appcache/* ${STEAMCMD_PATH}/.steam/logs/* ${STEAMCMD_PATH}/.steam/appcache/*
