FROM steamcmd/steamcmd:latest

# 设置ARK服务器的Steam ID和环境变量 (Beta Preaquatica版)
ENV STEAM_ID=376030
ENV APP_UPDATE="${STEAM_ID} -beta preaquatica"
ENV STEAM_USER="anonymous"
ENV INSTALL_DIR='/home/steam/arkserver'


# 下载和安装ARK服务器
RUN mkdir -p $INSTALL_DIR && \
    steamcmd +@sSteamCmdForcePlatformType windows +force_install_dir $INSTALL_DIR +login $STEAM_USER +app_update $APP_UPDATE validate +quit && \
    # 清理SteamCMD缓存文件
    rm -rf /home/steam/Steam/logs/* /home/steam/Steam/appcache/* /home/steam/.steam/logs/* /home/steam/.steam/appcache/*