FROM steamcmd/steamcmd:latest

# 构建参数，用于选择是否使用beta版本
ARG USE_BETA=false

# 设置ARK服务器的Steam ID和环境变量
# 如果USE_BETA为true，则使用beta preaquatica版本
ENV STEAM_ID=${USE_BETA:+"376030 -beta preaquatica"}${USE_BETA:-376030} \
    STEAM_USER=anonymous \
    INSTALL_DIR='/home/steam/arkserver'


# 下载和安装ARK服务器
RUN mkdir -p $INSTALL_DIR && \
    steamcmd +@sSteamCmdForcePlatformType windows +force_install_dir $INSTALL_DIR +login $STEAM_USER +app_update $STEAM_ID validate +quit && \
    # 清理SteamCMD缓存文件
    rm -rf /home/steam/Steam/logs/* /home/steam/Steam/appcache/* /home/steam/.steam/logs/* /home/steam/.steam/appcache/*