name: ASE Server Docker CI

on:
  push:
    branches:
      - wine

jobs:
  # 最终镜像
  ASE-Server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Free disk space
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: true
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build the Docker image
      run: |
        docker build . --file dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/ase-server:wine
    
    - name: Push Docker images
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/ase-server:wine 